---
apiVersion: v1
kind: Namespace
metadata:
  name: webhook
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook1-certificate
  namespace: webhook
spec:
  secretName: webhook1-certificate
  dnsNames:
  - admission-demo.webhook
  - admission-demo.webhook.svc
  - admission-demo.webhook.svc.cluster.local
  issuerRef:
    name: selfsigned

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: webhook
spec:
  selfSigned: {}
